from pydantic import BaseModel, Field
from typing import Optional


class ImportSchema(BaseModel):
    import_type_1: Optional[bool] = Field(None, description="Import type (CheckBox 1)")
    import_type_2: Optional[bool] = Field(None, description="Import type (CheckBox 2)")
    owner_name: Optional[str] = Field(None, description="Owner Details Owner Name")
    owner_id_abn_abncac_ccid: Optional[str] = Field(None, description="Owner ID ABN ABNCAC or CCID")
    owner_reference: Optional[str] = Field(None, description="Owner Reference")
    biosecurity_inspection_location: Optional[str] = Field(None, description="Biosecurity Inspection Location")
    hphone1: Optional[str] = Field(None, description="Home phone 1")
    hphone2: Optional[str] = Field(None, description="Home phone 2")
    wphone1: Optional[str] = Field(None, description="Work phone 1")
    wphone2: Optional[str] = Field(None, description="Work phone 2")
    mobile: Optional[str] = Field(None, description="Mobile phone")
    f1: Optional[str] = Field(None, description="Field F1")
    f2: Optional[str] = Field(None, description="Field F2")
    owner_email: Optional[str] = Field(None, description="Owner email")
    destination_port_code: Optional[str] = Field(None, description="Destination Port Code")
    invoice_term_type: Optional[str] = Field(None, description="Invoice Term Type")
    valuation_date: Optional[str] = Field(None, description="Valuation Date")
    header_valuation_advice_no: Optional[str] = Field(None, description="Header Valuation Advice No")
    eft_1: Optional[bool] = Field(None, description="EFT (CheckBox 1)")
    eft_2: Optional[bool] = Field(None, description="EFT (CheckBox 2)")
    amount1: Optional[str] = Field(None, description="Amount1")
    currency1: Optional[str] = Field(None, description="Currency1")
    amount2: Optional[str] = Field(None, description="Amount2")
    currency2: Optional[str] = Field(None, description="Currency2")
    amount3: Optional[str] = Field(None, description="Amount3")
    currency3: Optional[str] = Field(None, description="Currency3")
    amount4: Optional[str] = Field(None, description="Amount4")
    currency4: Optional[str] = Field(None, description="Currency4")
    amount5: Optional[str] = Field(None, description="Amount5")
    currency5: Optional[str] = Field(None, description="Currency5")
    amount6: Optional[str] = Field(None, description="Amount6")
    currency6: Optional[str] = Field(None, description="Currency6")
    amount7: Optional[str] = Field(None, description="Amount7")
    currency7: Optional[str] = Field(None, description="Currency7")
    amount8: Optional[str] = Field(None, description="Amount8")
    currency8: Optional[str] = Field(None, description="Currency8")
    amount9: Optional[str] = Field(None, description="Amount9")
    currency9: Optional[str] = Field(None, description="Currency9")
    t3: Optional[bool] = Field(None, description="T3 (CheckBox)")
    t4: Optional[bool] = Field(None, description="T4 (CheckBox)")
    declaration: Optional[str] = Field(None, description="Declaration")
    no: Optional[str] = Field(None, description="No")
    date1: Optional[str] = Field(None, description="Date1")
    airline_code: Optional[str] = Field(None, description="Airline Code")
    loading_port1: Optional[str] = Field(None, description="Loading Port 1")
    first_arrival_port1: Optional[str] = Field(None, description="First Arrival Port 1")
    discharge_port1: Optional[str] = Field(None, description="Discharge Port 1")
    first_arrival_date1: Optional[str] = Field(None, description="First Arrival Date 1")
    gross_weight1: Optional[str] = Field(None, description="Gross Weight 1")
    gross_weight_unit1: Optional[str] = Field(None, description="Gross Weight Unit 1")
    line_no1: Optional[str] = Field(None, description="Line No 1")
    master_air_waybill_no_row1: Optional[str] = Field(None, description="Master Air Waybill No Row 1")
    house_air_waybill_no_row1: Optional[str] = Field(None, description="House Air Waybill No Row 1")
    no_of_packages1: Optional[str] = Field(None, description="No of Packages 1")
    marks_numbers_description_row1: Optional[str] = Field(None, description="Marks Numbers Description Row 1")
    line_no2: Optional[str] = Field(None, description="Line No 2")
    master_air_waybill_no_row2: Optional[str] = Field(None, description="Master Air Waybill No Row 2")
    house_air_waybill_no_row2: Optional[str] = Field(None, description="House Air Waybill No Row 2")
    no_of_packages2: Optional[str] = Field(None, description="No of Packages 2")
    marks_numbers_description_row2: Optional[str] = Field(None, description="Marks Numbers Description Row 2")
    vessel_name: Optional[str] = Field(None, description="Vessel Name")
    vessel_id: Optional[str] = Field(None, description="Vessel ID")
    voyage_no: Optional[str] = Field(None, description="Voyage No")
    loading_port_2: Optional[str] = Field(None, description="Loading Port 2")
    first_arrival1: Optional[str] = Field(None, description="First Arrival 1")
    discharge_port: Optional[str] = Field(None, description="Discharge Port")
    first_arrival_date_2: Optional[str] = Field(None, description="First Arrival Date 2")
    gross_weight_2: Optional[str] = Field(None, description="Gross Weight 2")
    gross_weight_unit_2: Optional[str] = Field(None, description="Gross Weight Unit 2")
    line_no3: Optional[str] = Field(None, description="Line No 3")
    cargo_type_row1: Optional[str] = Field(None, description="Cargo Type Row 1")
    container_no_row1: Optional[str] = Field(None, description="Container No Row 1")
    ocean_bill_of_lading_no1: Optional[str] = Field(None, description="Ocean Bill of Lading No 1")
    house_bill_of_lading_no1: Optional[str] = Field(None, description="House Bill of Lading No 1")
    no_of_packages3: Optional[str] = Field(None, description="No of Packages 3")
    marks_numbers_description_row3: Optional[str] = Field(None, description="Marks Numbers Description Row 3")
    line_no4: Optional[str] = Field(None, description="Line No 4")
    cargo_type_row2: Optional[str] = Field(None, description="Cargo Type Row 2")
    container_no_row2: Optional[str] = Field(None, description="Container No Row 2")
    ocean_bill_of_lading_no2: Optional[str] = Field(None, description="Ocean Bill of Lading No 2")
    house_bill_of_lading_no2: Optional[str] = Field(None, description="House Bill of Lading No 2")
    no_of_packages4: Optional[str] = Field(None, description="No of Packages 4")
    marks_numbers_description_row4: Optional[str] = Field(None, description="Marks Numbers Description Row 4")
    loading_port_3: Optional[str] = Field(None, description="Loading Port 3")
    first_arrival_port_2: Optional[str] = Field(None, description="First Arrival Port 2")
    discharge_port_2: Optional[str] = Field(None, description="Discharge Port 2")
    dateb1: Optional[str] = Field(None, description="Date B1")
    monthb1: Optional[str] = Field(None, description="Month B1")
    yearb1: Optional[str] = Field(None, description="Year B1")
    parcel_post_card_nos: Optional[str] = Field(None, description="Parcel Post Card Nos")
    gross_weight_3: Optional[str] = Field(None, description="Gross Weight 3")
    gross_weight_unit_3: Optional[str] = Field(None, description="Gross Weight Unit 3")
    number_of_packages: Optional[str] = Field(None, description="Number of Packages")
    marks_numbers_description: Optional[str] = Field(None, description="Marks & Numbers description")
    department_receipt_for_goods_no: Optional[str] = Field(None, description="Department Receipt for Goods No")
    no_of_packages5: Optional[str] = Field(None, description="No of Packages 5")
    loading_port_4: Optional[str] = Field(None, description="Loading Port 4")
    first_arrival_port_3: Optional[str] = Field(None, description="First Arrival Port 3")
    discharge_port_3: Optional[str] = Field(None, description="Discharge Port 3")
    first_arrival_date_3: Optional[str] = Field(None, description="First Arrival Date 3")
    gross_weight_4: Optional[str] = Field(None, description="Gross Weight 4")
    gross_weight_unit_4: Optional[str] = Field(None, description="Gross Weight Unit 4")
    important_name: Optional[str] = Field(None, description="Important Name")
    delivery_address: Optional[str] = Field(None, description="Delivery Address")
    details_locality: Optional[str] = Field(None, description="Details Locality")
    state1: Optional[str] = Field(None, description="State 1")
    postcode1: Optional[str] = Field(None, description="Postcode 1")
    contact_phone_no: Optional[str] = Field(None, description="Contact Phone No")
    line_no1c: Optional[str] = Field(None, description="Line No 1C")
    supplier_id: Optional[str] = Field(None, description="Supplier ID")
    vendor_id_1: Optional[str] = Field(None, description="Vendor ID 1")
    supplier_name: Optional[str] = Field(None, description="Supplier Name")
    tariff_classification_no: Optional[str] = Field(None, description="Tariff Classification No")
    stat_code1: Optional[str] = Field(None, description="Stat Code 1")
    tc1: Optional[bool] = Field(None, description="TC1 (CheckBox)")
    valuation_basis_type1: Optional[str] = Field(None, description="Valuation Basis Type 1")
    treatment_code1: Optional[str] = Field(None, description="Treatment Code 1")
    gst_exemption_code1: Optional[str] = Field(None, description="GST Exemption Code 1")
    establishment_code1: Optional[str] = Field(None, description="Establishment Code 1")
    goods_descriptionc: Optional[str] = Field(None, description="Goods Description C")
    quantity1: Optional[str] = Field(None, description="Quantity 1")
    unit1: Optional[str] = Field(None, description="Unit 1")
    permit_number1: Optional[str] = Field(None, description="Permit Number 1")
    amountc1: Optional[str] = Field(None, description="Amount C1")
    currencyc1: Optional[str] = Field(None, description="Currency C1")
    pricerow1: Optional[str] = Field(None, description="Price Row 1")
    amountc2: Optional[str] = Field(None, description="Amount C2")
    currencyc2: Optional[str] = Field(None, description="Currency C2")
    pricerow2: Optional[str] = Field(None, description="Price Row 2")
    amountc3: Optional[str] = Field(None, description="Amount C3")
    currencyc3: Optional[str] = Field(None, description="Currency C3")
    pricerow3: Optional[str] = Field(None, description="Price Row 3")
    amountc4: Optional[str] = Field(None, description="Amount C4")
    currencyc4: Optional[str] = Field(None, description="Currency C4")
    origin_country1: Optional[str] = Field(None, description="Origin Country 1")
    preference_origin_country1: Optional[str] = Field(None, description="Preference Origin Country 1")
    preference_scheme_type1: Optional[str] = Field(None, description="Preference Scheme Type 1")
    preference_rule_type1: Optional[str] = Field(None, description="Preference Rule Type 1")
    instrument_type1: Optional[str] = Field(None, description="Instrument Type 1")
    instrument_number1: Optional[str] = Field(None, description="Instrument Number 1")
    instrument_type2: Optional[str] = Field(None, description="Instrument Type 2")
    instrument_number2: Optional[str] = Field(None, description="Instrument Number 2")
    additional_information: Optional[str] = Field(None, description="Additional Information")
    producer_code: Optional[str] = Field(None, description="Producer Code")
    line_no1c_2: Optional[str] = Field(None, description="Line No 1C (2)")
    supplier_id_2: Optional[str] = Field(None, description="Supplier ID (2)")
    vendor_id_1_2: Optional[str] = Field(None, description="Vendor ID 1 (2)")
    supplier_name_2: Optional[str] = Field(None, description="Supplier Name (2)")
    tariff_classification_no_2: Optional[str] = Field(None, description="Tariff Classification No (2)")
    stat_code_2: Optional[str] = Field(None, description="Stat Code (2)")
    tc2: Optional[bool] = Field(None, description="TC2 (CheckBox)")
    valuation_basis_type_2: Optional[str] = Field(None, description="Valuation Basis Type (2)")
    treatment_code_2: Optional[str] = Field(None, description="Treatment Code (2)")
    gst_exemption_code_2: Optional[str] = Field(None, description="GST Exemption Code (2)")
    establishment_code2: Optional[str] = Field(None, description="Establishment Code 2")
    goods_descriptionc_2: Optional[str] = Field(None, description="Goods Description C (2)")
    quantity_2: Optional[str] = Field(None, description="Quantity (2)")
    unit_2: Optional[str] = Field(None, description="Unit (2)")
    permit_number2: Optional[str] = Field(None, description="Permit Number 2")
    amountc1_2: Optional[str] = Field(None, description="Amount C1 (2)")
    currencyc1_2: Optional[str] = Field(None, description="Currency C1 (2)")
    pricerow1_2: Optional[str] = Field(None, description="Price Row 1 (2)")
    amountc2_2: Optional[str] = Field(None, description="Amount C2 (2)")
    currencyc2_2: Optional[str] = Field(None, description="Currency C2 (2)")
    pricerow2_2: Optional[str] = Field(None, description="Price Row 2 (2)")
    amountc3_2: Optional[str] = Field(None, description="Amount C3 (2)")
    currencyc3_2: Optional[str] = Field(None, description="Currency C3 (2)")
    pricerow3_2: Optional[str] = Field(None, description="Price Row 3 (2)")
    amountc4_2: Optional[str] = Field(None, description="Amount C4 (2)")
    currencyc4_2: Optional[str] = Field(None, description="Currency C4 (2)")
    origin_country_2: Optional[str] = Field(None, description="Origin Country (2)")
    preference_origin_country_2: Optional[str] = Field(None, description="Preference Origin Country (2)")
    preference_scheme_type_2: Optional[str] = Field(None, description="Preference Scheme Type (2)")
    preference_rule_type_2: Optional[str] = Field(None, description="Preference Rule Type (2)")
    instrument_type1_2: Optional[str] = Field(None, description="Instrument Type 1 (2)")
    instrument_number1_2: Optional[str] = Field(None, description="Instrument Number 1 (2)")
    instrument_type2_2: Optional[str] = Field(None, description="Instrument Type 2 (2)")
    instrument_number2_2: Optional[str] = Field(None, description="Instrument Number 2 (2)")
    additional_information_2: Optional[str] = Field(None, description="Additional Information (2)")
    producer_code_2: Optional[str] = Field(None, description="Producer Code (2)")


def mapToFillingSchema(sectiona, sectionb, sections):
    import_schema = {
        'Import type': sectiona.import_declaration_type,
    'Owner Details Owner Name': sectiona.owner_name,
    'Owner ID ABN ABNCAC or CCID': sectiona.owner_id,
    'Owner Reference': sectiona.owner_reference,
    'Biosecurity Inspection Location': sectiona.aqis_inspection_location,
    'Hphone1': sectiona.contact_details,
    'Hphone2': sectiona.contact_details,
    'Wphone1': sectiona.contact_details,
    'Wphone2': sectiona.contact_details,
    'Mobile': sectiona.contact_details,
    'F1': sectiona.contact_details,
    'F2': sectiona.contact_details,
    # 'Owner email': sectiona.contact_details,
    'Destination Port Code': sectiona.destination_port_code,
    'Invoice Term Type': sectiona.invoice_term_type,
    'Valuation Date': sectiona.valuation_date,
    'Header Valuation Advice No': sectiona.header_valuation_advice_number,
    # 'EFT': sectiona.invoice_term_type,
    # 'EFT': sectiona.invoice_term_type,
    'Declaration': sectiona.declaration_signature,
    'Date1': sectiona.valuation_date,
    'Amount1': sectiona.invoice_term_type,
    'Currency1': sectiona.invoice_term_type,
    }
